apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssh
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - name: master
        image: ruediste/sshd
        # command:
        #   - /usr/sbin/sshd
        #   - -De
        ports:
        - containerPort: 22
      #  readinessProbe:
          # tcpSocket:
          #   port: 22
          # periodSeconds: 10
          # timeoutSeconds: 5
          # successThreshold: 2
          # failureThreshold: 5
        env:
        volumeMounts:
        - mountPath: /root/.ssh/
          name: ssh-dir
        - mountPath: /etc/ssh/
          name: ssh-host-keys
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 20Mi
      volumes:
      - name: ssh-dir
        secret:
          secretName: ssh-keys
          defaultMode: 0600
      - name: ssh-host-keys
        secret:
          secretName: ssh-host-keys
          defaultMode: 0600
